Add `from_f32_px_truncated` and `from_f64_px_truncated` methods
servo/app_units pull request #60
Opened 2024-12-26 03:53 UTC by Asun0204

2025-01-08 13:49 UTC, Loirooriol requested changes

2025-01-08 13:49 UTC, Loirooriol commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
There is already a `scale_by_trunc`, so I would call this `from_f32_px_trunc`.

2025-01-08 13:49 UTC, Loirooriol commented on src/app_unit.rs
> +        let float = (px * AU_PER_PX as f32).floor();
This should use `trunc()` instead of `floor()`.

2025-01-09 13:12 UTC, Asun0204 commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
The input parameter type is dismatch. This is the way that `f64 -> f64 * AU_PER_PX -> truncate -> i32`. Instead of  `scale_by_trunc` complete the way that `f64 -> i32 -> f64 -> truncate -> f64 * AU_PER_PX`. Truncate operation should be between AU_PER_PX and i32.

2025-01-09 13:14 UTC, Asun0204 commented on src/app_unit.rs
> +        let float = (px * AU_PER_PX as f32).floor();
fixed

2025-01-09 13:14 UTC, Loirooriol commented on src/app_unit.rs
> +    assert_eq!(Au::from_f32_px_truncate(5.0), Au(300));
Also need to rename these

2025-01-10 01:13 UTC, Asun0204 commented on src/app_unit.rs
> +    assert_eq!(Au::from_f32_px_truncate(5.0), Au(300));
Sorry. This fault is fixed and test unit is passed

2025-01-10 01:14 UTC, Loirooriol commented on src/app_unit.rs
> +    pub fn from_f32_px_by_trunc(px: f32) -> Au {
There is `scale_by` and `scale_by_trunc`.
So here it should be `from_f32_px` and `from_f32_px_trunc`, not `from_f32_px_by_trunc`.

2025-01-10 01:14 UTC, Loirooriol commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
I have no idea of what you are trying to say here.

2025-01-10 01:25 UTC, Asun0204 commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
Do you mean that I would implement `scale_by_trunc` method using `from_f32_px_trunc`?

2025-01-10 01:28 UTC, Loirooriol commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
No. I'm only referring to `scale_by_trunc` to be consistent with the naming.

2025-01-10 01:37 UTC, Asun0204 commented on src/app_unit.rs
> +    pub fn from_f32_px_truncate(px: f32) -> Au {
Ok, I know it and the name has been modified.

2025-01-10 01:45 UTC, Asun0204 commented on src/app_unit.rs
> +    pub fn from_f32_px_by_trunc(px: f32) -> Au {
fixed

2025-03-06 14:34 UTC, Loirooriol approved these changes
OK things are looking good, we can start landing

2025-03-06 14:36 UTC, merged

2025-03-06 14:38 UTC, Loirooriol commented
@jdm Can you publish please? This already bumped the version